### ISSUE TITLE
My Milestone Progress

### ISSUE THREAD

**Issue by tompetersjr** [azurestandard/issue-milestone-tracker#3]
# Overview

Tracking of tompetersjr's repositories for milestone `My Milestone`.

### Overall Stats

:checkered_flag: **Percentage Completed:** *70*%
:pencil2: **Issues Opened:** *3*
:closed_book: **Issues Closed:** *7*
:heavy_check_mark: **Issues Total:** *10*

### Milstone Details by Repository:

Repository | Details
:-- | :--
**[api-spec](https://github.com/tompetersjr/api-spec/milestones/My%Milestone)** | :page_facing_up: **Description:** *This is my milestone's description.*
 | :checkered_flag: **Percentage Completed:** *100*%
 | :pencil2: **Opened:** *2*
 | :closed_book: **Closed:** *2*
 | :calendar: **Due On:** *March 11, 2016* (13 days from now)
 | 
**[api](https://github.com/tompetersjr/api/milestones/My%Milestone)** | :page_facing_up: **Description:** *This is my milestone's description.*
 | :checkered_flag: **Percentage Completed:** *67*%
 | :pencil2: **Opened:** *1*
 | :closed_book: **Closed:** *3*
 | :calendar: **Due On:** *March 11, 2016* (13 days from now)
 | 
**[website](https://github.com/tompetersjr/website/milestones/My%Milestone)** | :page_facing_up: **Description:** *This is my milestone's description.*
 | :checkered_flag: **Percentage Completed:** *100*%
 | :pencil2: **Opened:** *0*
 | :closed_book: **Closed:** *2*
 | :calendar: **Due On:** *March 11, 2016* (13 days from now)
 | 

# Aggregated Data

## :chart: Repositories

Repository | Issues Opened | Issues Closed | Pulls Open | Pulls Closed | Open Totals | Closed Totals | Totals
:-- | --: | --: | --: | --: | --: | --: | --:
**api-spec** | 1 | 1 | 1 | 1 | **2** | **2** | **4** (*50*%)
**api** | 0 | 3 | 1 | 0 | **1** | **3** | **4** (*67*%)
**website** | 0 | 0 | 0 | 2 | **0** | **2** | **2** (*100*%)
**Totals** | **1** | **4** | **2** | **3** |

## :chart: Assignees

Assignee | Issues Opened | Issues Closed | Pulls Open | Pulls Closed | Open Totals | Closed Totals | Totals
:-- | --: | --: | --: | --: | --: | --: | --:
**tompetersjr** | 1 | 4 | 2 | 3 | **3** | **7** | **10** (*70*%)
**Totals** | **1** | **4** | **2** | **3** |

## :chart: Labels

Label | Issues Opened | Issues Closed | Pulls Open | Pulls Closed | Open Totals | Closed Totals | Totals
:-- | --: | --: | --: | --: | --: | --: | --:
**bug** | 1 | 2 | 1 | 1 | **2** | **3** | **5** (*60*%)
**enhancement** | 0 | 1 | 0 | 0 | **0** | **1** | **1** (*100*%)
**feature request** | 1 | 1 | 0 | 0 | **1** | **1** | **2** (*50*%)
**question** | 2 | 0 | 0 | 0 | **2** | **0** | **2** (*0*%)

## :chart: Days

Opened On | Total | <---------- Past 7 Work Day Totals  ----------> | Closed On | Total
:-- | --: | :--: | :-- | --:
**2016-02-24** | 1 | | **2016-02-25** | 2
**2016-02-23** | 1 | | **2016-02-24** | 2
**2016-02-22** | 1 | | **2016-02-23** | 2
 |  | | **2016-02-22** | 1

# Repository Details

### api-spec

- :pencil2: open
  - :bust_in_silhouette: tompetersjr
    - [ ] Issue [#4](https://github.com/tompetersjr/api-spec/pull/4): Spelling problems
    - [ ] Pull [#3](https://github.com/tompetersjr/api-spec/pull/3): Add username to spec
- :closed_book: closed
  - :bust_in_silhouette: tompetersjr
    - [X] Pull [#2](https://github.com/tompetersjr/api-spec/pull/2): ~~Update Readme.md~~
    - [X] Issue [#1](https://github.com/tompetersjr/api-spec/pull/1): ~~Fix Description~~

### api

- :pencil2: open
  - :bust_in_silhouette: tompetersjr
    - [ ] Pull [#4](https://github.com/tompetersjr/api/issues/4): Implement username to be returned in json response
- :closed_book: closed
  - :bust_in_silhouette: tompetersjr
    - [X] Issue [#3](https://github.com/tompetersjr/api/pull/3): ~~Added login endpoint~~
    - [X] Issue [#2](https://github.com/tompetersjr/api/pull/2): ~~Added docementation~~
    - [X] Issue [#1](https://github.com/tompetersjr/api/pull/1): ~~Fixed spelling issue~~

### website

- :closed_book: closed
  - :bust_in_silhouette: tompetersjr
    - [X] Pull [#3](https://github.com/tompetersjr/website/pull/2): ~~Created login screen~~
    - [X] Pull [#2](https://github.com/tompetersjr/website/pull/1): ~~Added docementation~~

# Notes

This issue is automatically updated by a python script. This script goes through all `tompetersjr` repositories and lists issues under the `My Milestone` milestone.  There is no need to check off individual issues. The script will is manually run to update the issue list periodically. This script will check off closed items.  Comments on this issue will be preserved between updates.

:calendar: **Last Updated:** *February 26, 2016  03:04:41 PM* **by** *tompetersjr*

**Comment by tompetersjr** [comment]
Links above are for example purposes only.  They do not work.
